version: "3.3"
services:
  backend:
    container_name: django_resfule_vue_backend
    build:
      context: backend
      dockerfile: backend.dev.dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - django_resfule_vue_network
  db:
    container_name: django_resfule_vue_db
    image: postgres:12.0-alpine
    volumes:
      - django_resfule_vue_db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=django_db
    networks:
      - django_resfule_vue_network

networks:
  django_resfule_vue_network:
    driver: bridge
volumes:
  django_resfule_vue_db_data:
#  api:
#    container_name: api
#    build: ./vue_backend
#    command: python manage.py runserver 0.0.0.0:8000
##    command: gunicorn -c gunicorn_config.py vuebackend.wsgi:application
##    command: gunicorn vuebackend.wsgi:application --bind 127.0.0.1:8005
#    volumes:
#      - ./vue_backend/:/usr/src/api/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - db
#      - redis
#    networks:
#      - django-nginx